---
title: "IDS 19 mars"
output: html_document
---

14h28 

players <- c("Andy Murray", "Rafael Nadal", "Stan Wawrinka", 
             "Novak Djokovic", "Roger Federer")
grand_slam_win <- c(9,15,5,12,18)
win_percentage <- c(78.07, 82.48, 63.96, 82.77, 81.80)
(mat <- cbind(grand_slam_win, win_percentage))
rownames(mat) = players
mat [2,2]
mat [5,1]
mat ["Roger Federer",]
mat [,2]
mat[-5,]
mat[-c(2,5),]

*Combiner 2 matrices. Nombres de cases, nombre de lignes, n colonnes.
A = matrix(1:4,2,2)
B = matrix(1:6,2,3)
cbind(A,B)

n = 4
diag(n)
20*diag(n)

*Grading : via to-do list on Github. Next HW may be tricky. Participation will exclusively be via Piazza forum.* 
*Important to understand vector and matrices. Arrays not so much*

# list elements and list initialization
num_vec <- c(188, 140)
char_vec <- c("Height", "Weight", "Length")
logic_vec <- rep(TRUE, 8)
my_mat <- matrix(0, nrow = 5, ncol = 5)
(my_list <- list(num_vec, char_vec, logic_vec, my_mat))

#How to see 188?
my_list[1]
my_list[[1]]
*TRUE : 
my_list[[1]][1]
#How to extract 3rd row of the list?
(my_list <- list(num_vec, char_vec, logic_vec, my_mat))
my_list[[4]][3,]
#the two elements of 2nd row?
my_list[[2]][-3]
my_list[[2]][c(1,2)]
#Entire rows
my_list[[2]]
my_list[[4]]

#DIVERS
my_list[1]
my_list[[1]] + 1


#DATAFRAME section on coursebook 

### Creation

players <- c("Andy Murray", "Rafael Nadal", "Stan Wawrinka", 
             "Novak Djokovic", "Roger Federer")

grand_slam_win <- c(9, 15, 5, 12, 18)

date_of_birth <- c("15 May 1987", "3 June 1986", "28 March 1985", 
                  "22 May 1987", "8 August 1981")

country <- c("Great Britain", "Spain", "Switzerland", 
            "Serbia", "Switzerland")
ATP_ranking <- c(1, 2, 3, 4, 5)

prize_money <- c(60449649, 85920132, 30577981, 109447408, 104445185)

tennis <- data.frame(date_of_birth, grand_slam_win, country, 
                    ATP_ranking, prize_money)

dimnames(tennis)[[1]] <- players

tennis
tennis$prize_money
tennis[1,]
tennis[,4]
tennis["Novak Djokovic",]

###CHAPTER5 
#Now we talk about coding, programming etc.
x$y$z -> extract info of z

*output
x = 2
*asking whether x really = 2
x == 2
x > 0
x <= 2
*What about this?
x = c(3,1,5)
x == 1
y = c(3,1,4)
x == y
*Watch out
x = c(3,1,5)
z = c(3,1)
x == z
*Weird but...
g = c(3,1,3,1)
h = c(3,1)
g == h
*What about inequality of vector ?
g = c(3,1,3,1)
i = c(3,1,2,4)
g > i 

#Logical operators, see in online textbook for list 
* Is x diff than 2 ?
x = 2
y = 3
!(x == 2)
* Is x > 1 AND y < 1 ? 
x > 1 && y < 1
* Is X > 1 OR y < 1 ? 
x > 1 || y < 1
*RIDDLE ->
!(x < 4 || x > 0) && y > 2
(y == 3 || x > 1 + 1) == 2
!xor((x < 3 && x > 0) || y < 10, !(FALSE))

*Only first number with &&, two if &. So keep going with one "and" or "bar"
x = c(10,2)
y = c(2,5)
y > 0 && x < 5 
y > 0 & x < 5

#IF ELSE
x = -2 
abs(x)
*or...
x = -2 
if (x < 0){
x = -x
}
x
*self try
x= 34
if (x < 0){
x = -x
}else{
x = 10000
}
x

*Program an even or odd detector ? (NB : 3%%2 -> Modulus, x= number is to be played around)
x = 17
if (x %% 2 == 0){
cat(paste("The number", x, "is even"))
}else{
cat(paste("The number", x, "is odd"))
}
x

